# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c541edfa88409af26dfc01a4fe1c7a9e22ca584fe5c2b85dcd756b66c67b08d384edbf890f4c71f25410bf7040f305650012e183304294646ae15c64b76673

test:
  secret_key_base: eec74689de7301248011140fa3e19351776c1c48fa6c451306783811015d91ba0419791e106335305e42924aded3e57a4108e20a8d7a3b9222f332195079338e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
